(define (rational a b) (list (/ a (gcd a b)) (/ b (gcd a b))))
(define (rat-num r) (car r))
(define (rat-denom r) (car (cdr r)))
(define (rat-= r1 r2) 
  (if (= (car r1) (car r2))
    (= (car (cdr r1)) (car (cdr r2)))
    #f
    )
  )
(define rat-0 (rational 0 1))
(define (rat-+ r1 r2) (rational (+ (* (rat-num r2) (rat-denom r1)) (* (rat-num r1) (rat-denom r2))) (* (rat-denom r1) (rat-denom r2))))
(define (rat-- r) (list (* -1 (car r)) (car (cdr r))))
(define rat-1 (rational 1 1))
(define (rat-* r1 r2)(rational (* (rat-num r1) (rat-num r2)) (* (rat-denom r1 ) (rat-denom r2)))) 
(define (rat-/ r) (list (car (cdr r)) (car r)))
