(define (fix2 f)
  ((lambda (x) (f (lambda (y) ((x x) y)))) (lambda (x) (f (lambda (y) ((x x) y)))))
  )
(define (fact5 a) 
  ((fix2 (lambda (x) 
          (lambda (y)
            (if (= y 1)
              1
              (* y (x (- y 1))) 
              )
            )
          )
        ) a )
  )
