(define (pivot x l a b)
  (if (null? l) (cons a b)
    (if (string<? (car l) x)
      (pivot x (cdr l) (cons (car l) a) b)
      (pivot x (cdr l) a (cons (car l) b))
      )
    )
  )
(define (my-sort l)
  (if (null? l)
    '()
    (let ((z (pivot (car l) (cdr l) '() '())))
      (append (my-sort (car z))
              (cons (car l) (my-sort (cdr z)))
              )
      )
    )
  )

